name: Generate Readme and Release Action
description: 'Generates readme from `action.yaml` and Release the action using the given release config'
inputs:
  token:
    description: 'git token to use for the run'
    required: true
  ref:
    description: 'ref to checkout to release from'
    required: false
    default: ${{ github.base_ref }}
  toggle-admins:
    description: 'If true, this action will disable the `include administrators` setting in branch protection for this branch, and re-enable it after release. Re-enabling is run using always()'
    required: false
    default: false
  release-config:
    description: 'The release configuration to use for the release. Set this to `@unsupervised/release-config-javascript-actions` for javascript actions'
    required: false
    default: '@unsupervised/release-config-composite-actions'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.ref }}
    - name: Dry run to get next version
      id: semantic-release-dry-run
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        dry_run: true
        extends: ${{ inputs.release-config }}
    - shell: bash
      run: |
        git status
    - uses: bitflight-devops/github-action-readme-generator@v1.0.12a
      with:
        action: ${{ github.workspace }}/action.yaml
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        pretty: true
        versioning_enabled: true
        version_override: v${{ steps.semantic-release-dry-run.outputs.new_release_major_version }}
    - shell: bash
      run: |
        git status
    - uses: Unsupervisedcom/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true'
      with:
        token: ${{ inputs.token }}
        include-admins: false
    - id: semantic-release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      with:
        extends: ${{ inputs.release-config }}
    - shell: bash
      run: |
        git status
    - uses: Unsupervisedcom/action-branch-protection-bot@v1
      if: inputs.toggle-admins == 'true' && always()  # Force to always run this step to ensure "include administrators" is always turned back on
      with:
        token: ${{ inputs.token }}
        include-admins: true