name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - action.yaml
jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # this makes the semantic-release git plugin push as the automation user, which allows us to bypass branch protection
          token: ${{ secrets.DEPLOYER_CI_TOKEN }}
      - uses: Unsupervisedcom/action-release-action@main
        with:
          token: ${{ secrets.DEPLOYER_CI_TOKEN }}